#!/bin/bash

# --- template --- {{{
readonly cf="\\033[0m"
readonly red="\\033[0;31m"
readonly green="\\033[0;32m"
readonly yellow="\\033[0;33m"

err() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${red}ERROR${cf}]: $1" 1>&2
  exit 1
}

warn() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${yellow}WARNING${cf}]: $1"
}

info() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][INFO]: $1 "
}

succ() {
  local _date
  _date=$(showdate)
  echo -e "[$_date][${green}SUCCESS${cf}]: $1"
}

showdate() {
  local _date
  _date=$(date +%d-%H.%M)
  echo "$_date"
}

cleanup() {
  info "cleanup.."
}
#}}}

show_help() {
  cat <<'EOF'

USAGE:
  tfref [options] <resource|data>

OPTIONS:
  -h: help
  -t: test: bash tfref_test
  -f: open_read_file_line_up: tfref -f $file_path $line

SUPPORTED TYPE:
  aws, datadog, data_datadog, data_aws

EXAMPLE:
  tfref aws_instance
  tfref datadog_monitor
  tfref data.aws_instance
  tfref data.datadog_api_key
  tfref -f "./ec2.tf" 20

EOF
  exit 0
}

fix_open_arg() {
  if [[ "$2" =~ ^data_.* ]]; then
    echo "$1" | cut -f 1,2 -d '.'
  else
    echo "$1" | cut -f 1 -d '.'
  fi
}

get_open_cmd() {
  case "$(uname | tr "[:lower:]" "[:upper:]")" in
  *'linux'*) echo 'xdg-open' ;;
  *'bsd'*) echo 'xdg-open' ;;
  *'darwin'*) echo 'open' ;;
  *) echo 'open' ;;
  esac
}

is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

open_run() {
  local open_cmd
  open_cmd="$(get_open_cmd)"
  if ! is_exists "$open_cmd"; then
    err "$open_cmd command is not found"
  fi
  url="$(get_open_url "$1")"
  if [[ -n "$url" ]]; then
    $open_cmd "$url"
  fi
  exit 0
}

get_open_url() {
  local type arg
  type="$(get_type "$1")"
  arg="$(fix_open_arg "$1" "$type")"
  case $type in
  "aws")
    echo "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/${arg//aws_/}"
    ;;
  "datadog")
    echo "https://registry.terraform.io/providers/datadog/datadog/latest/docs/resources/${arg//datadog_/}"
    ;;
  "data_aws")
    echo "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/${arg//data.aws_/}"
    ;;
  "data_datadog")
    echo "https://registry.terraform.io/providers/datadog/datadog/latest/docs/data-sources/${arg//data.datadog_/}"
    ;;
  "*")
    err "not supported type"
    ;;
  esac
}

# Support types:
# data hoge {}
# resource fuga {}
open_read_file_line_up() {
  arg="$(read_file_line_up "$2" "$3")"
  if [[ -n "$arg" ]]; then
    open_run "$arg"
  fi
  exit 0
}

read_file_line_up() {
  local file line
  declare -a lines
  file="$1"
  line="$2"
  i=0
  while read -r l; do
    lines+=("$l")
    ((i++))
  done <"$file"

  for ((j = line; 0 < j; j--)); do
    line_type="$(get_line_type "${lines[$j - 1]}")"
    if [[ "$line_type" != "not-specified" ]]; then
      arg="$(echo "${lines[$j - 1]}" | cut -f 2 -d " " | sed -e "s/\"//g")"
      if [[ "$line_type" == "data" ]]; then
        arg="data.$arg"
      fi
      cat <<<"$arg"
      break
    fi
  done
}

get_line_type() {
  if [[ "$1" =~ ^resource.* ]]; then
    echo "resource"
  elif [[ "$1" =~ ^data.* ]]; then
    echo "data"
  else
    echo "not-specified"
  fi
}

get_data_type() {
  if [[ "$1" =~ ^data\.aws_.* ]]; then
    echo "data_aws"
  elif [[ "$1" =~ ^data\.datadog_.* ]]; then
    echo "data_datadog"
  else
    err "not supported: $1"
  fi
}

get_type() {
  if [[ "$1" =~ ^data\..* ]]; then
    get_data_type "$1"
  elif [[ "$1" =~ ^aws_.* ]]; then
    echo "aws"
  elif [[ "$1" =~ ^datadog_.* ]]; then
    echo "datadog"
  else
    err "not supported type"
  fi
}

# run
while getopts ":hft" o; do
  case "${o}" in
  h)
    show_help
    exit 0
    ;;
  t)
    if [ -f "tfref_test" ]; then
      info "testing"
      # shellcheck disable=SC1091
      . "tfref_test"
    else
      err "tfref_test is not found"
    fi
    exit 0
    ;;
  f)
    if [[ "$#" -eq 3 && "$1" == "-f" ]]; then
      open_read_file_line_up "$1" "$2" "$3"
    else
      show_help
    fi
    exit 0
    ;;
  *)
    err "invalid option"
    show_help
    exit 1
    ;;
  esac
done

if [[ "$#" -ne 1 ]]; then
  show_help
else
  open_run "$1"
fi
